"""audio_overview.py — render a 2-voice podcast from an overview script.

Parses a SPEAKER_A: / SPEAKER_B: script generated by Brain.audio_overview_script,
synthesizes each line with a distinct Kokoro voice, concatenates with short
silences between turns, writes a single .wav file alongside the source script.

Voices configurable via env:
    CHLOE_VOICE_A — host voice (default: af_heart)
    CHLOE_VOICE_B — expert voice (default: am_michael)

Kokoro model + voices files are auto-discovered relative to this script's
directory. Same paths jarvis.py uses.

Used by the /podcast command in brain_wiring.py.
"""

import os
import re
from pathlib import Path
import numpy as np


# Voice IDs. Pair of clearly-different Kokoro voices for podcast-style contrast.
# af_heart   = American female, warm
# am_michael = American male, measured
VOICE_A = os.environ.get("CHLOE_VOICE_A", "af_heart").strip() or "af_heart"
VOICE_B = os.environ.get("CHLOE_VOICE_B", "am_michael").strip() or "am_michael"


# ─── Kokoro lazy init ────────────────────────────────────────────────────────
_kokoro = None
_kokoro_attempted = False


def _find_kokoro_files():
    """Locate kokoro-v1.0.onnx and voices-v1.0.bin.

    Priority:
      1. Explicit env vars KOKORO_MODEL_PATH / KOKORO_VOICES_PATH (matches jarvis.py)
      2. Auto-discovery in common subfolders next to this script
    """
    # ── 1. Env vars (preferred — matches whatever jarvis.py uses) ──
    env_model = os.environ.get("KOKORO_MODEL_PATH", "").strip()
    env_voices = os.environ.get("KOKORO_VOICES_PATH", "").strip()
    if env_model and env_voices:
        m, v = Path(env_model), Path(env_voices)
        if m.exists() and v.exists():
            return m, v
        print(f"[overview] env paths set but files missing: "
              f"model={m.exists()} voices={v.exists()}", flush=True)

    # ── 2. Auto-discovery ──
    base = Path(__file__).parent
    # Most common: kokoro_models/ subfolder (jarvis.py default), but also try
    # plain models/ and the script's own directory.
    candidates = [
        base / "kokoro_models",
        base / "models",
        base,
        base.parent / "kokoro_models",
        base.parent / "models",
    ]
    model = None
    voices = None
    searched = []
    for d in candidates:
        searched.append(str(d))
        if not d.exists():
            continue
        for fn in d.iterdir():
            n = fn.name.lower()
            if model is None and n.startswith("kokoro") and n.endswith(".onnx"):
                model = fn
            if voices is None and n.startswith("voices") and n.endswith(".bin"):
                voices = fn
    if model is None or voices is None:
        print(f"[overview] kokoro files not found. Searched: {searched}",
              flush=True)
    return model, voices


def _get_kokoro():
    """Lazy load the Kokoro engine. Returns None if unavailable."""
    global _kokoro, _kokoro_attempted
    if _kokoro_attempted:
        return _kokoro
    _kokoro_attempted = True
    try:
        from kokoro_onnx import Kokoro
    except ImportError:
        print("[overview] Kokoro not installed — pip install kokoro-onnx soundfile",
              flush=True)
        return None
    model, voices = _find_kokoro_files()
    if model is None or voices is None:
        print(f"[overview] Kokoro model files not found near {Path(__file__).parent}",
              flush=True)
        return None
    print(f"[overview] loading Kokoro for podcast render (model={model.name})",
          flush=True)
    try:
        _kokoro = Kokoro(str(model), str(voices))
    except Exception as e:
        print(f"[overview] Kokoro init failed: {type(e).__name__}: {e}", flush=True)
        return None
    return _kokoro


# ─── Script parsing ──────────────────────────────────────────────────────────
SPEAKER_RE = re.compile(r'^(SPEAKER_[AB]):\s*(.+?)\s*$')


def parse_script(text: str) -> list:
    """Extract (speaker, content) tuples. Skips YAML frontmatter, markdown
    headers, and the markdown horizontal rules between sections.

    Multi-line continuations (where a turn wraps to the next line without a
    new SPEAKER_X: prefix) are appended to the current turn.

    Frontmatter is detected ONLY at the very start of the file: a leading
    "---" line followed by content and a closing "---". Subsequent "---"
    lines elsewhere in the file are markdown horizontal rules, not
    frontmatter delimiters, and are ignored.
    """
    lines = text.splitlines()

    # Detect leading YAML frontmatter (must start at line 0).
    start_idx = 0
    if lines and lines[0].strip() == '---':
        for i in range(1, len(lines)):
            if lines[i].strip() == '---':
                start_idx = i + 1
                break

    turns = []
    current = None

    for raw in lines[start_idx:]:
        line = raw.rstrip()
        # Markdown horizontal rules (between sections) — skip
        if line.strip() == '---':
            if current:
                turns.append(current)
                current = None
            continue
        # Markdown headers
        if line.lstrip().startswith('#'):
            if current:
                turns.append(current)
                current = None
            continue

        m = SPEAKER_RE.match(line)
        if m:
            if current:
                turns.append(current)
            current = (m.group(1), m.group(2).strip())
        elif current and line.strip():
            speaker, prev = current
            current = (speaker, prev + ' ' + line.strip())

    if current:
        turns.append(current)
    return [(s, c) for s, c in turns if c]


# ─── Rendering ───────────────────────────────────────────────────────────────
def render_script(script_path,
                  output_path=None,
                  voice_a: str = None,
                  voice_b: str = None,
                  silence_ms: int = 350,
                  speed: float = 1.0) -> dict:
    """Render an overview script to a single WAV file with two voices.

    Args:
        script_path: path to a .md script (with SPEAKER_A: / SPEAKER_B: lines).
        output_path: where to write the .wav. Defaults to script_path with
            .wav extension.
        voice_a, voice_b: Kokoro voice IDs. Defaults to VOICE_A / VOICE_B
            module constants (configurable via env).
        silence_ms: gap between speaker turns in milliseconds.
        speed: Kokoro speech rate (1.0 = normal).

    Returns: dict with path, duration_min, exchanges_rendered, exchanges_failed,
        errors (list of error strings, one per failed turn).
    """
    script_path = Path(script_path)
    if not script_path.exists():
        raise FileNotFoundError(f"Script not found: {script_path}")

    voice_a = voice_a or VOICE_A
    voice_b = voice_b or VOICE_B

    text = script_path.read_text(encoding='utf-8')
    turns = parse_script(text)
    if not turns:
        raise ValueError("Script has no SPEAKER_A: / SPEAKER_B: turns")

    engine = _get_kokoro()
    if engine is None:
        raise RuntimeError(
            "Kokoro not available. Check that kokoro_onnx is installed and "
            "model files (kokoro-v1.0.onnx, voices-v1.0.bin) are next to "
            "audio_overview.py or in a 'models' subfolder."
        )

    if output_path is None:
        output_path = str(script_path.with_suffix('.wav'))

    sample_rate = None
    chunks = []
    silence = None
    errors = []

    for i, (speaker, line) in enumerate(turns):
        voice = voice_a if speaker == 'SPEAKER_A' else voice_b
        try:
            samples, sr = engine.create(line, voice=voice, speed=speed, lang='en-us')
            if sample_rate is None:
                sample_rate = sr
                silence = np.zeros(int(sr * silence_ms / 1000), dtype=samples.dtype)
            chunks.append(samples)
            if i < len(turns) - 1:
                chunks.append(silence)
        except Exception as e:
            errors.append(f"turn {i + 1} ({speaker}, voice={voice}): {type(e).__name__}: {e}")
            print(f"[overview] failed turn {i + 1}: {e}", flush=True)

    if not chunks or sample_rate is None:
        raise RuntimeError(
            f"All {len(turns)} turns failed to synthesize. "
            f"First error: {errors[0] if errors else 'unknown'}"
        )

    full = np.concatenate(chunks)
    duration_s = len(full) / sample_rate

    try:
        import soundfile as sf
    except ImportError:
        raise RuntimeError("soundfile not installed — pip install soundfile")
    sf.write(output_path, full, sample_rate)

    return {
        'path': output_path,
        'duration_s': round(duration_s, 1),
        'duration_min': round(duration_s / 60, 1),
        'exchanges_rendered': len(turns) - len(errors),
        'exchanges_failed': len(errors),
        'errors': errors,
        'voice_a': voice_a,
        'voice_b': voice_b,
        'sample_rate': sample_rate,
    }


def autoplay(wav_path) -> bool:
    """Try to open the WAV in the system default audio app. Windows-friendly.
    Non-fatal — returns True on success, False otherwise.
    """
    try:
        os.startfile(str(wav_path))  # type: ignore[attr-defined]  # Windows-only
        return True
    except AttributeError:
        # Non-Windows fallback
        try:
            import subprocess
            subprocess.Popen(['xdg-open', str(wav_path)])
            return True
        except Exception:
            return False
    except Exception as e:
        print(f"[overview] autoplay failed: {e}", flush=True)
        return False
