"""brain_graph.py - extract a force-directed graph from the wiki.

Pure compute, no HTTP. Called by brain_http.py to serve the graph view at
/brain-graph.html. Each markdown file in BRAIN.wiki_dir/** is a node;
[[wikilinks]] inside the page body are edges.

Public API:
    compute_graph(wiki_dir, include_facts=False, since_ts=None)
        -> dict {nodes: [...], edges: [...], stats: {...}}
    read_page(wiki_dir, rel)
        -> {ok, text, frontmatter, path}

v2 schema (2026-05-18) adds per-node fields the new brain-graph UI needs:
    mtime        - st_mtime epoch seconds (recently-edited pulse, time slider)
    source_type  - heuristic: obsidian/brave/dropped_in/finance/daily/chloe (badge color)
    orphan       - True if real AND degree <= 1 (orphan-highlight filter)
    body_size    - byte length (size scaling without re-stat on the client)
    fm_type      - frontmatter `type:` if present (vs path-based `type`)

And stats:
    orphan_count, recent_changes (last 10 mtimes), last_event (from event_bus),
    embed_coverage (None unless wiki_embedding is importable + reachable).
"""

import os
import re
import time
from pathlib import Path

# [[link]] or [[link|alt text]]
LINK_RE = re.compile(r"\[\[([^\]\|]+)(?:\|[^\]]+)?\]\]")

# Page kinds we care about (subdirectories under wiki/)
KNOWN_TYPES = ("entities", "concepts", "sources", "comparisons", "explorations",
               "daily", "episodic", "raw")

# Frontmatter: very small parser — only the leading `--- ... ---` block, only
# top-level `key: value` lines. No nested YAML. Good enough for our pages.
_FM_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _parse_frontmatter(text: str) -> dict:
    m = _FM_RE.match(text)
    if not m:
        return {}
    out: dict = {}
    for line in m.group(1).splitlines():
        line = line.rstrip()
        if not line or line.startswith('#') or ':' not in line:
            continue
        k, _, v = line.partition(':')
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _source_type_for(rel_id: str, fm: dict) -> str:
    """Best-effort: where did this page come from? Drives the badge color
    in the brain-graph UI. Frontmatter wins; path heuristics fall back."""
    fm_src = (fm.get('source_type') or '').strip().lower()
    if fm_src:
        return fm_src

    parts = rel_id.split('/')
    if not parts:
        return 'unknown'
    top = parts[0]
    name = parts[-1]

    if top == 'daily':
        return 'daily'
    if top == 'episodic':
        # CONTEXT-*.md are auto-generated by daily_context.bat
        return 'episodic'
    if top == 'sources':
        # Heuristic names match the frontmatter values used elsewhere in
        # the codebase (e.g. _persist_brave_to_wiki sets 'web_search',
        # daily_finance_ingest sets 'finance_news') so files without
        # frontmatter still land in the same UI bucket.
        if name.startswith('web_'):
            return 'web_search'
        if name.startswith('finance_'):
            return 'finance_news'
        if name.startswith('dropin_'):
            return 'dropped_in'
        return 'external'
    if top in ('entities', 'concepts', 'comparisons', 'explorations'):
        return 'chloe_generated'
    return 'unknown'


def _slug_for_link(target: str, current_type: str) -> str:
    """Resolve a [[link]] target into a canonical node id.

    Wikilinks in this brain look like:
        [[qmd]]                   -> bare slug, resolve relative to current type
        [[entities/qmd]]          -> typed path
        [[entities/qmd.md]]       -> typed path with extension
    Returns the canonical id used as node.id (no extension, normalized).
    """
    t = target.strip().replace("\\", "/")
    if t.endswith(".md"):
        t = t[:-3]
    if "/" not in t:
        # Bare slug — assume same type as the page that linked from it
        t = f"{current_type}/{t}"
    return t


def compute_graph(wiki_dir, include_facts: bool = False,
                  since_ts: float | None = None) -> dict:
    """Walk wiki_dir/**/*.md and return {nodes, edges, stats}.

    Args:
        wiki_dir: brain/wiki root
        include_facts: also include `facts/*.md` from the brain root
            (sibling of wiki/). Opt-in until verified.
        since_ts: if set, only include nodes with mtime >= since_ts
            (powers the time-slider growth animation on the UI).

    Node fields (v2):
        id         'entities/qmd', 'concepts/rag', etc.
        label      slug
        type       parent dir
        real       True for actual files, False for dangling wikilink targets
        in_deg, out_deg, degree, size
        mtime      epoch seconds (0 for ghosts)
        body_size  bytes (0 for ghosts)
        source_type heuristic — see _source_type_for
        orphan     real AND degree <= 1
        fm_type    frontmatter `type:` if present
    Edges:
        source, target  (target may be a ghost)
    """
    wiki_dir = Path(wiki_dir)
    if not wiki_dir.exists():
        return {"nodes": [], "edges": [],
                "stats": {"error": f"wiki_dir not found: {wiki_dir}"}}

    brain_root = wiki_dir.parent  # facts/ sits beside wiki/
    nodes_by_id = {}
    edges = []

    # Ignored ghosts: one slug per line in <brain_root>/.ignore_ghosts.
    # Wikilinks pointing to these targets are dropped entirely (no edge,
    # no ghost node). Comments (#) and blank lines OK.
    ignore_ghosts: set = set()
    ignore_path = brain_root / ".ignore_ghosts"
    if ignore_path.exists():
        try:
            for line in ignore_path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#"):
                    ignore_ghosts.add(line)
        except Exception:
            pass

    # File set: wiki/**/*.md, plus optionally facts/*.md (mounted under a
    # synthetic 'facts/' prefix so node ids stay disambiguated).
    file_records: list[tuple[str, Path]] = []
    for path in sorted(wiki_dir.rglob("*.md")):
        rel = str(path.relative_to(wiki_dir).with_suffix("")).replace("\\", "/")
        if rel in ("index", "log", "gaps", "SESSIONS"):
            continue
        file_records.append((rel, path))
    if include_facts:
        facts_dir = brain_root / 'facts'
        if facts_dir.exists():
            for path in sorted(facts_dir.rglob("*.md")):
                rel = "facts/" + str(path.relative_to(facts_dir).with_suffix("")).replace("\\", "/")
                file_records.append((rel, path))

    # First pass: every .md file is a real node.
    for rel_id, path in file_records:
        parts = rel_id.split("/")
        if len(parts) < 2:
            page_type = "other"
            slug = parts[0]
        else:
            page_type = parts[0]
            slug = "/".join(parts[1:])

        try:
            st = path.stat()
            mtime = st.st_mtime
            body_size = st.st_size
        except OSError:
            mtime, body_size = 0.0, 0

        # Time-slider filter: drop nodes the user hasn't slid to yet.
        if since_ts is not None and mtime < since_ts:
            continue

        # Read enough to grab frontmatter — small, no caching needed.
        fm: dict = {}
        try:
            text_head = path.read_text(encoding="utf-8", errors="replace")[:2048]
            fm = _parse_frontmatter(text_head)
        except Exception:
            pass

        nodes_by_id[rel_id] = {
            "id":          rel_id,
            "label":       slug,
            "type":        page_type,
            "real":        True,
            "in_deg":      0,
            "out_deg":     0,
            "mtime":       mtime,
            "body_size":   body_size,
            "source_type": _source_type_for(rel_id, fm),
            "fm_type":     fm.get("type") or "",
        }

    # Second pass: parse links to build edges.
    for rel_id, path in file_records:
        if rel_id not in nodes_by_id:
            continue
        src_type = nodes_by_id[rel_id]["type"]
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        for m in LINK_RE.finditer(text):
            tgt = _slug_for_link(m.group(1), src_type)
            if tgt == rel_id:
                continue  # ignore self-loops
            # If target doesn't exist as a real file, create a ghost node —
            # unless the user has explicitly ignored it.
            if tgt not in nodes_by_id:
                if tgt in ignore_ghosts:
                    continue  # drop the entire wikilink — no edge, no ghost
                parts = tgt.split("/")
                ghost_type = parts[0] if len(parts) > 1 else "ghost"
                nodes_by_id[tgt] = {
                    "id":          tgt,
                    "label":       parts[-1],
                    "type":        ghost_type,
                    "real":        False,
                    "in_deg":      0,
                    "out_deg":     0,
                    "mtime":       0.0,
                    "body_size":   0,
                    "source_type": "ghost",
                    "fm_type":     "",
                }
            edges.append({"source": rel_id, "target": tgt})
            nodes_by_id[rel_id]["out_deg"] += 1
            nodes_by_id[tgt]["in_deg"] += 1

    # Degree, size, orphan-flag.
    for n in nodes_by_id.values():
        deg = n["in_deg"] + n["out_deg"]
        n["degree"] = deg
        n["size"] = max(6, min(36, 6 + deg * 2))
        n["orphan"] = bool(n["real"]) and deg <= 1

    nodes = sorted(nodes_by_id.values(), key=lambda n: -n["degree"])

    # Stats: counts, type counts, source-type counts, recent change list.
    type_counts: dict = {}
    source_counts: dict = {}
    for n in nodes:
        type_counts[n["type"]] = type_counts.get(n["type"], 0) + 1
        source_counts[n["source_type"]] = source_counts.get(n["source_type"], 0) + 1

    real_nodes = [n for n in nodes if n["real"]]
    recent = sorted(real_nodes, key=lambda n: -n["mtime"])[:10]
    recent_changes = [
        {"id": n["id"], "mtime": n["mtime"], "source_type": n["source_type"]}
        for n in recent
    ]

    # Best-effort embed coverage from wiki_embedding. Don't fail the graph
    # request if it can't be reached.
    embed_coverage = None
    try:
        from wiki_embedding import WikiEmbeddingStore  # type: ignore
        store = WikiEmbeddingStore()
        total = store.count_pages()
        embedded = store.count_embedded()
        embed_coverage = {
            "embedded": int(embedded),
            "total": int(total),
            "ratio": (embedded / total) if total else 0.0,
        }
    except Exception:
        pass

    # Latest event_bus event — gives the UI a 'watcher heartbeat' indicator.
    last_event = None
    try:
        from event_bus import last_event as _last_event  # type: ignore
        last_event = _last_event()
    except Exception:
        pass

    stats = {
        "node_count":     len(nodes),
        "edge_count":     len(edges),
        "real_count":     sum(1 for n in nodes if n["real"]),
        "ghost_count":    sum(1 for n in nodes if not n["real"]),
        "orphan_count":   sum(1 for n in nodes if n.get("orphan")),
        "ignored_ghost_count": len(ignore_ghosts),
        "type_counts":    type_counts,
        "source_counts":  source_counts,
        "recent_changes": recent_changes,
        "embed_coverage": embed_coverage,
        "last_event":     last_event,
        "computed_at":    time.time(),
        "include_facts":  bool(include_facts),
        "since_ts":       since_ts,
    }
    return {"nodes": nodes, "edges": edges, "stats": stats}


def ghost_slugs_below_degree(wiki_dir, max_degree: int = 1) -> list[str]:
    """Ids of ghost (dangling-wikilink) nodes whose degree <= max_degree.

    Ghosts only ever receive links (out_deg == 0), so degree == the number
    of real pages referencing the dead [[wikilink]]. Degree-1 ghosts are the
    long tail of one-off typos / never-written stubs that make up most of the
    graph's clutter. Powers the bulk ghost-ignore UI. Already-ignored ghosts
    don't appear in compute_graph output, so repeated prunes are idempotent.
    """
    g = compute_graph(wiki_dir)
    return sorted(
        n["id"] for n in g["nodes"]
        if not n.get("real") and n.get("degree", 0) <= max_degree
    )


def read_page(wiki_dir, rel_id: str) -> dict:
    """Return raw markdown for a node id, path-safe scoped to wiki_dir.

    rel_id must be a slash-delimited path under wiki_dir (e.g. 'entities/qmd').
    The synthetic 'facts/' prefix resolves to the sibling facts/ directory.

    Returns {ok, text, frontmatter, path, error?}.
    """
    wiki_dir = Path(wiki_dir).resolve()
    brain_root = wiki_dir.parent
    rel_id = (rel_id or "").strip().strip("/")
    if rel_id.lower().endswith(".md"):
        rel_id = rel_id[:-3]
    if not rel_id or ".." in rel_id.split("/"):
        return {"ok": False, "error": "invalid rel_id"}

    # Allow facts/ as a sibling-of-wiki escape hatch.
    if rel_id.startswith("facts/"):
        base = brain_root
    else:
        base = wiki_dir

    candidate = (base / (rel_id + ".md")).resolve()
    try:
        candidate.relative_to(base)
    except ValueError:
        return {"ok": False, "error": "path escapes base dir"}
    if not candidate.exists():
        return {"ok": False, "error": f"page not found: {rel_id}",
                "ghost": True, "path": str(candidate)}
    try:
        text = candidate.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        return {"ok": False, "error": f"read failed: {type(e).__name__}: {e}"}
    return {
        "ok":          True,
        "text":        text,
        "frontmatter": _parse_frontmatter(text),
        "path":        str(candidate),
        "mtime":       candidate.stat().st_mtime,
    }


# ─── CLI for quick smoke testing ─────────────────────────────────────────────
if __name__ == "__main__":
    import json
    import sys
    from os import environ
    root = Path(environ.get("CHLOE_BRAIN_ROOT", r"C:\Chloe\brain"))
    wiki = root / "wiki"
    if "--page" in sys.argv:
        rel = sys.argv[sys.argv.index("--page") + 1]
        print(json.dumps(read_page(wiki, rel), indent=2, default=str))
    else:
        include_facts = "--facts" in sys.argv
        g = compute_graph(wiki, include_facts=include_facts)
        print(json.dumps(g["stats"], indent=2, default=str))
        print(f"sample top-5 nodes by degree:")
        for n in g["nodes"][:5]:
            print(f"  {n['id']:40s} type={n['type']:12s} src={n['source_type']:14s} deg={n['degree']}")
